- platform: darksky
  api_key: !secret darksky_apikey
  monitored_conditions:
    - summary
    - icon
    - precip_probability
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min

#- platform: darksky
#  pi_key: !secret darksky_apikey
##  forecast:
##    - 1
##    - 2
##    - 3
##    - 4
##    - 5
##    - 6
##    - 7
#  monitored_conditions:
#    - summary
#    - icon
##    - nearest_storm_distance
##    - nearest_storm_bearing
##    - precip_type
##    - precip_intensity
#    - precip_probability
#    - temperature
##    - apparent_temperature
##    - dew_point
#    - wind_speed
#    - wind_bearing
##    - cloud_cover
#    - humidity
#    - pressure
##    - visibility
##    - ozone
##    - minutely_summary
##    - hourly_summary
##    - daily_summary
#    - temperature_max
#    - temperature_min
#    - apparent_temperature_max
#    - apparent_temperature_min
##    - precip_intensity_max  

- platform: mqtt
  state_topic: "cmnd/garage-door-sensor/POWER1"
  name: garage_door_status
  payload_on: "ON"
  payload_off: "OF"

- platform: template
  sensors:
    garage_status:
      friendly_name: 'Garage Door Status'
      value_template: >-
        {%- if is_state('sensor.garage_door_status', 'ON') -%}
          Closed
        {%- elif is_state('sensor.garage_door_status', 'OFF') -%}
          Open
        {%- else -%}
          Unknown
        {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.garage_door_status", "ON") -%}
          mdi:garage
        {%- else -%}
          mdi:garage-open
        {%- endif %}
